
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Maps port 80 in the container to port 8080 on your host
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=StarshipDb;User=mssql;Password=YourStrongPassword!;Trusted_Connection=True;TrustServerCertificate=True

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: starhipproject-db-1
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword!
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
